name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Auto-assign issue or PR
      uses: pozil/auto-assign-issue@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        assignees: xiaoshaziYA,BXJZDXMM,VMware12tom,Win13Pro
