name: Auto Assign Developer and Add Label

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  handle-issue-events:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Check event type and process
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 处理新创建的 issue
          if [ "${{ github.event_name }}" = "issues" ] && [ "${{ github.event.action }}" = "opened" ]; then
            echo "Processing new issue..."
            ISSUE_NUMBER=${{ github.event.issue.number }}
            COMMENT="@${{ github.actor }} 您好，已收到您的问题，我们会尽快处理。\n@xiaoshaziYA 有新的问题需要确认。"
            
            # 添加评论
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -X POST \
                 -d "{\"body\":\"$COMMENT\"}" \
                 "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
            
            # 添加标签
            curl -s -H "Authorization: token $GITHUB_TOKEN" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -X POST \
                 -d '{"labels":["×等待开发者确认"]}' \
                 "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/labels"
          
          # 处理评论事件
          elif [ "${{ github.event_name }}" = "issue_comment" ] && [ "${{ github.event.action }}" = "created" ]; then
            echo "Processing comment..."
            
            # 获取评论内容和评论者信息
            COMMENT_BODY=$(echo '${{ toJSON(github.event.comment.body) }}' | jq -r .)
            COMMENTER="${{ github.event.comment.user.login }}"
            COMMENT_ID="${{ github.event.comment.id }}"
            ISSUE_NUMBER=${{ github.event.issue.number }}
            
            # 检查评论内容是否包含"确认"
            if echo "$COMMENT_BODY" | grep -q "确认"; then
              echo "Comment contains '确认'"
              
              # 检查评论者是否有仓库写入权限
              PERMISSION_CHECK=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                "https://api.github.com/repos/${{ github.repository }}/collaborators/${COMMENTER}/permission")
              
              PERMISSION_LEVEL=$(echo "$PERMISSION_CHECK" | jq -r '.permission')
              
              # 如果有写入权限或以上权限（admin, write, maintain）
              if [ "$PERMISSION_LEVEL" = "admin" ] || [ "$PERMISSION_LEVEL" = "write" ] || [ "$PERMISSION_LEVEL" = "maintain" ]; then
                echo "User $COMMENTER has permission level: $PERMISSION_LEVEL"
                
                # 获取当前issue的标签和分配信息
                CURRENT_ISSUE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                  -H "Accept: application/vnd.github.v3+json" \
                  "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}")
                
                HAS_CONFIRMED_LABEL=$(echo "$CURRENT_ISSUE" | jq '.labels[] | select(.name == "✓已确认") | length > 0')
                
                # 如果已经有"已确认"标签
                if [ "$HAS_CONFIRMED_LABEL" = "true" ]; then
                  echo "Issue already confirmed, responding to duplicate confirmation..."
                  
                  # 回复评论，引用该评论
                  DUPLICATE_RESPONSE="> @$COMMENTER 确认\n\n已由其他管理人员确认，无须再次确认。"
                  
                  curl -s -H "Authorization: token $GITHUB_TOKEN" \
                       -H "Accept: application/vnd.github.v3+json" \
                       -X POST \
                       -d "{\"body\":\"$DUPLICATE_RESPONSE\"}" \
                       "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
                
                else
                  echo "First confirmation, updating labels..."
                  
                  # 移除"等待开发者确认"标签（如果存在）
                  curl -s -H "Authorization: token $GITHUB_TOKEN" \
                       -H "Accept: application/vnd.github.v3+json" \
                       -X DELETE \
                       "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/labels/×等待开发者确认" || true
                  
                  # 添加"已确认"标签
                  curl -s -H "Authorization: token $GITHUB_TOKEN" \
                       -H "Accept: application/vnd.github.v3+json" \
                       -X POST \
                       -d '{"labels":["✓已确认"]}' \
                       "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/labels"
                  
                  echo "Label updated to '✓已确认'"
                fi
                
                # 只有有权限的用户才被分配issue
                echo "Assigning issue to $COMMENTER (has permission: $PERMISSION_LEVEL)"
                
                # 获取当前已分配的人员
                CURRENT_ASSIGNEES=$(echo "$CURRENT_ISSUE" | jq '[.assignees[].login]')
                
                # 如果评论者还没有被分配，则添加到分配列表
                if ! echo "$CURRENT_ASSIGNEES" | jq -r ".[]" | grep -q "^$COMMENTER$"; then
                  # 添加新分配者到现有分配列表
                  NEW_ASSIGNEES=$(echo "$CURRENT_ASSIGNEES" | jq --arg committer "$COMMENTER" '. + [$committer] | unique')
                  
                  # 更新分配
                  curl -s -H "Authorization: token $GITHUB_TOKEN" \
                       -H "Accept: application/vnd.github.v3+json" \
                       -X POST \
                       -d "{\"assignees\":$NEW_ASSIGNEES}" \
                       "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/assignees"
                  
                  echo "Assigned issue to $COMMENTER"
                else
                  echo "$COMMENTER is already assigned to this issue"
                fi
                
              else
                echo "User $COMMENTER does not have sufficient permissions (current: $PERMISSION_LEVEL), skipping assignment and label changes"
                
                # 回复无权限的用户
                NO_PERMISSION_RESPONSE="> @$COMMENTER 确认\n\n抱歉，您没有足够的权限来确认此issue。只有具有写入权限的管理人员才能进行确认操作。"
                
                curl -s -H "Authorization: token $GITHUB_TOKEN" \
                     -H "Accept: application/vnd.github.v3+json" \
                     -X POST \
                     -d "{\"body\":\"$NO_PERMISSION_RESPONSE\"}" \
                     "https://api.github.com/repos/${{ github.repository }}/issues/${ISSUE_NUMBER}/comments"
              fi
            fi
          fi
